### ISSUE TITLE
UI: Handle commas and decimals as input

### ISSUE THREAD

**Issue by philc** [thumbtack/abba#12]
Sometimes one is working with numbers which are formatted with commas and decimal places, e.g. 1,157.00. If you paste a number like that into trials or successes, you get NaN. It would be a nice usability improvement to strip commas and ".00" decimal strings from the input, rather than making the user do it. This becomes very tedious when done repeatedly.

**Comment by philc** [comment]
Also, trim the whitespace around the input values. If you input "123  ", this causes an exception.

**Comment by gostevehoward** [comment]
Hey Phil, I fixed these over on my fork, https://github.com/gostevehoward/abba. I no longer have maintainer access to this repo. You can use the demo on that fork, https://gostevehoward.github.io/abba/demo/abba.html. (The "live demo" on thumbtack.com was also taken down at some point.) Let me know if it solves your problem.

If any maintainers here are actively invested in updating this repo, I can make a pull request, but I'm guessing the best option is to just migrate over to my fork.

**Comment by tgnourse** [comment]
@gostevehoward I gave you write access again. Not sure why it went away, but feel free to merge the fixes back in!

**Comment by jeffkirk1** [comment]
Hey guys,

I’m still getting notifications from your Github project changes. Just FYI. 

Jeff Kirk

**Comment by gostevehoward** [comment]
Pulled the seven-month-old commits in from my fork, finally :)
